import {resetForgot} from './apps/reducers/auth/authForgot';
import {resetLogin} from './apps/reducers/auth/authLogin';
import {userLogout} from './apps/reducers/auth/authLogout';
import {resetRegister} from './apps/reducers/auth/authRegister';
import {resetCartCount} from './apps/reducers/cartCount';
import {resetCartData} from './apps/reducers/cartData';
import {resetCartItemDecrement} from './apps/reducers/cartDecrement';
import {resetCartItemIncrement} from './apps/reducers/cartIncrement';
import {removeCartReset} from './apps/reducers/cartRemove';
import {resetSelectedCategoryData} from './apps/reducers/categoriesData';
import {resetCategoryData} from './apps/reducers/category/categories';
import {resetChangePassword} from './apps/reducers/changepass';
import {resetCheckOut} from './apps/reducers/checkout';
import {resetOrders} from './apps/reducers/orders';
import {resetMyProductsData} from './apps/reducers/product/myProduct';
import {resetProductDetailsData} from './apps/reducers/product/productDetails';
import {resetProductData} from './apps/reducers/product/productIndex';
import {resetProductNewArrivalData} from './apps/reducers/product/productNewArrivals';
import {resetProductSlidesData} from './apps/reducers/product/productSlides';
import {resetProductTrendingData} from './apps/reducers/product/productTrending';
import {resetUserData} from './apps/reducers/userData';
import {resetUserItemCount} from './apps/reducers/userItemCount';
import {resetWishlistAdd} from './apps/reducers/wishlistAdd';
import {resetWishlistCount} from './apps/reducers/wishlistCount';
import {resetWishlistItemsShow} from './apps/reducers/wishlistItemShow';
import {resetWishlistRemove} from './apps/reducers/wishlistRemove';

export const globalResetActions = () => {
  return dispatch => {
    dispatch(userLogout());
    dispatch(resetLogin());
    dispatch(resetRegister());
    dispatch(resetProductData());
    dispatch(resetCategoryData());
    dispatch(resetProductDetailsData());
    dispatch(resetSelectedCategoryData());
    dispatch(resetCartCount());
    dispatch(resetWishlistCount());
    dispatch(resetUserItemCount());
    dispatch(resetWishlistItemsShow());
    dispatch(resetUserData());
    dispatch(resetCartData());
    dispatch(resetCartItemIncrement());
    dispatch(resetCartItemDecrement());
    dispatch(resetMyProductsData());
    dispatch(resetChangePassword());
    dispatch(resetWishlistAdd());
    dispatch(resetWishlistRemove());
    dispatch(removeCartReset());
    dispatch(resetCheckOut());
    dispatch(resetOrders());
    dispatch(resetForgot());
    dispatch(resetProductSlidesData());
    dispatch(resetProductNewArrivalData());
    dispatch(resetProductTrendingData());
  };
};
