// Auth
export const USER_LOGIN = 'Auth/USER_LOGIN';
export const USER_LOGIN_REQUEST = 'Auth/USER_LOGIN_REQUEST';
export const USER_LOGIN_COMPLETED = 'Auth/USER_LOGIN_COMPLETED';
export const USER_LOGIN_ERROR = 'Auth/USER_LOGIN_ERROR';

export const USER_REGISTER = 'Auth/USER_REGISTER';
export const USER_REGISTER_REQUEST = 'Auth/USER_REGISTER_REQUEST';
export const USER_REGISTER_COMPLETED = 'Auth/USER_REGISTER_COMPLETED';
export const USER_REGISTER_ERROR = 'Auth/USER_REGISTER_ERROR';

export const USER_LOGOUT = 'Auth/USER_LOGOUT';
export const USER_LOGOUT_REQUEST = 'Auth/USER_LOGOUT_REQUEST';
export const USER_LOGOUT_COMPLETED = 'Auth/USER_LOGOUT_COMPLETED';
export const USER_LOGOUT_ERROR = 'Auth/USER_LOGOUT_ERROR';

export const PRODUCT_DATA = 'Product/PRODUCT_DATA';
export const PRODUCT_DATA_REQUEST = 'Product/PRODUCT_DATA_REQUEST';
export const PRODUCT_DATA_COMPLETED = 'Product/PRODUCT_DATA_COMPLETED';
export const PRODUCT_DATA_ERROR = 'Product/PRODUCT_DATA_ERROR';
