// Auth
export const USER_LOGIN = 'Auth/USER_LOGIN';
export const USER_LOGIN_REQUEST = 'Auth/USER_LOGIN_REQUEST';
export const USER_LOGIN_COMPLETED = 'Auth/USER_LOGIN_COMPLETED';
export const USER_LOGIN_ERROR = 'Auth/USER_LOGIN_ERROR';

export const USER_REGISTER = 'Auth/USER_REGISTER';
export const USER_REGISTER_REQUEST = 'Auth/USER_REGISTER_REQUEST';
export const USER_REGISTER_COMPLETED = 'Auth/USER_REGISTER_COMPLETED';
export const USER_REGISTER_ERROR = 'Auth/USER_REGISTER_ERROR';

export const USER_LOGOUT = 'Auth/USER_LOGOUT';
export const USER_LOGOUT_REQUEST = 'Auth/USER_LOGOUT_REQUEST';
export const USER_LOGOUT_COMPLETED = 'Auth/USER_LOGOUT_COMPLETED';
export const USER_LOGOUT_ERROR = 'Auth/USER_LOGOUT_ERROR';

// PRODUCT > index
export const PRODUCT_DATA = 'Product/PRODUCT_DATA';
export const PRODUCT_DATA_REQUEST = 'Product/PRODUCT_DATA_REQUEST';
export const PRODUCT_DATA_COMPLETED = 'Product/PRODUCT_DATA_COMPLETED';
export const PRODUCT_DATA_ERROR = 'Product/PRODUCT_DATA_ERROR';

// PRODUCT > details
export const PRODUCT_DETAILS_DATA = 'Product/PRODUCT_DETAILS_DATA';
export const PRODUCT_DETAILS_DATA_REQUEST =
  'Product/PRODUCT_DETAILS_DATA_REQUEST';
export const PRODUCT_DETAILS_DATA_COMPLETED =
  'Product/PRODUCT_DETAILS_DATA_COMPLETED';
export const PRODUCT_DETAILS_DATA_ERROR = 'Product/PRODUCT_DETAILS_DATA_ERROR';

// category > index
export const CATEGORY_DATA = 'Category/CATEGORY_DATA';
export const CATEGORY_DATA_REQUEST = 'Category/CATEGORY_DATA_REQUEST';
export const CATEGORY_DATA_COMPLETED = 'Category/CATEGORY_DATA_COMPLETED';
export const CATEGORY_DATA_ERROR = 'Category/CATEGORY_DATA_ERROR';

// category > data
export const CATEGORY_DETAILS_DATA = 'Category/CATEGORY_DETAILS_DATA';
export const CATEGORY_DETAILS_DATA_REQUEST =
  'Category/CATEGORY_DETAILS_DATA_REQUEST';
export const CATEGORY_DETAILS_DATA_COMPLETED =
  'Category/CATEGORY_DETAILS_DATA_COMPLETED';
export const CATEGORY_DETAILS_DATA_ERROR =
  'Category/CATEGORY_DETAILS_DATA_ERROR';

// cart count
export const CART_COUNT = 'Cart/CART_COUNT';
export const CART_COUNT_REQUEST = 'Cart/CART_COUNT_REQUEST';
export const CART_COUNT_COMPLETED = 'Cart/CART_COUNT_COMPLETED';
export const CART_COUNT_ERROR = 'Cart/CART_COUNT_ERROR';

// add to cart
export const ADD_TO_CART = 'Cart/ADD_TO_CART';
export const ADD_TO_CART_REQUEST = 'Cart/ADD_TO_CART_REQUEST';
export const ADD_TO_CART_COMPLETED = 'Cart/ADD_TO_CART_COMPLETED';
export const ADD_TO_CART_ERROR = 'Cart/ADD_TO_CART_ERROR';
